version: "3.9"

services:
  nextjs:
    build: ./nextjs
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
    depends_on:
      - db
    volumes:
      - ./nextjs:/app
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: